#!/usr/bin/env python
# coding: utf-8

# Game to help develop speed when typing for python.coding

#Import Libraries
import time
from hashlib import new
import random



#List of common keyboard strokes for programmers
list_ =  [ "*","(",")","_","+",
         "{","}","|","[","]","\\",
         ":",'"',"'",";","'",
         "<",">","?",",",".","?",
         "%","#","!","~","`" ]


# Initialise Input
new_input = ""
scores = 0
count = 0
keystroke_count = 11

print("\n")
print("<-------------------------------------->\n\n\n")

#User input
user_range = input("--------------- Press Enter ------------\n\n")
if user_range == "":
    user_range = keystroke_count
elif int(user_range) > keystroke_count:
    keystroke_count = int(user_range)

#Countdown
time.sleep(.3)

print("\n")
print("3\n\n")

time.sleep(1)
print("2\n\n")

time.sleep(1)
print("1\n")

time.sleep(1)


print("> GO! >\n")

#Start the clock
start_time = time.perf_counter()

# Game will continue untile the user types "quit" or if count gets to 10
while new_input != "quit" and count < keystroke_count :

    #Randomly choose a stroke from the list_
    key_ = random.choice(list_)
    print("-------\n")
    print(f"   {key_}\n")
    print("-------\n")

    #User inputs the matching key
    new_input = input("")
    count += 1

    #If the user input matches the key add 1 to total score
    if new_input == key_:
        scores += 1

#Once loop is complete, stop the timer
stop_time = time.perf_counter()

#Calculate score and time paramaters and print outcome

total_time = round(stop_time - start_time,2)
total_score = round((scores / count) * 100 ,2)

#Encourage player dialog
print ("<-------------------------------------->\n")
if new_input != "quit":

#High Score
    if total_time < (keystroke_count * 1.35) and total_score == 100:
        print("High Score !!!\n")
    if total_score == 100:
        print("Perfect Accuracy\n")
    if total_score >= 80 and total_score < 100:
        print("Good Accuracy\n")
    if total_time < (keystroke_count * 1.6) and total_score > 85 :
        print("Great job speedy fingers!\n")

    #Bad Score
    if total_score == 0:
        print("Want to try that again?..\n")
    if total_score < 75:
        print("You can do better?")
    if total_time > (keystroke_count * 1.8):
        print("Pick up the pace")

    #Print Results
    print ("<-------------------------------------->\n")
    print(f"Time: {total_time} seconds")
    print(f"Accuracy {total_score}%")

# Keyboard Training by Dan Isaacman 