#!/usr/bin/env python
# coding: utf-8

# Game to help develop speed when typing for python.coding

from hashlib import new
import random
import time


#List of common keyboard strokes
list_ =  [ "*","(",")","_","+",
         "{","}","|","[","]","\\",
         ":",'"',"'",";","'",
         "<",">","?",",",".","?",
         "%","#","!","~","`" ]

# Initialise Input
new_input = ""
scores = 0
count = 0

print("\n")
print("<-------------------------------------->\n\n\n")

#User input
user_range = input("--------------- Press Enter ------------\n\n")

#Countdown
time.sleep(.3)

print("3\n\n")

time.sleep(1)
print("2\n\n")

time.sleep(1)
print("1\n\n")

time.sleep(1)


print("<-------------------GO!---------------->\n\n")

#Start the clock
start_time = time.perf_counter()

# Game will continue untile the user types "quit" or if count gets to 10
while new_input != "quit" and count < 11 :

    #Randomly choose a stroke from the list_
    key_ = random.choice(list_)
    print("_______\n")
    print(f"   {key_}")
    print("_______\n")

    #User inputs the matching key
    new_input = input("")
    count += 1

    #If the user input matches the key add 1 to total score
    if new_input == key_:
        scores += 1

#Once loop is complete, stop the timer
stop_time = time.perf_counter()

#Calculate score and time paramaters and print outcome

total_time = round(stop_time - start_time,2)
total_score = round((scores / count) * 100 ,2)

#Encourage player dialog
print ("<-------------------------------------->\n")
if new_input != "quit":

#High Score
    if total_time < 15 and total_score == 100:
        print("High Score !!!\n")
    if total_score == 100:
        print("Perfect Accuracy\n")
    if total_score >= 80:
        print("Good Accuracy\n")
    if total_time < 18 and total_score > 75 :
        print("Great job speedy fingers!\n")

    #Bad Score
    if total_score == 0:
        print("Want to try that again?..\n")
    if total_score < 75:
        print("You can do better?")
    if total_time > 20:
        print("Pick up the pace")

    #Print Results
    print ("<-------------------------------------->\n")
    print(f"Time: {total_time} seconds")
    print(f"Accuracy {total_score}%")

# Keyboard Training by Dan Isaacman 