#!/usr/bin/env python
# coding: utf-8

# Game to help develop speed when typing for python.coding

#Import Libraries
import time
from hashlib import new
import random
import requests
import json

list_ = {"syntax": 
            [ "*","(",")","_","+",
            "{","}","|","[","]","\\",
            ":",'"',"'",";","'",
            "<",">","?",",",".","?",
            "%","#","!","~","`","^","&" 
            ],
                    
        "git" :
            ["cd","cd ~","cd ../","ls","pwd"
            "touch","echo","mkdir", "git add .",
            "git commit -m", "git push", "git clone",
            "git checkout", "git pull", "code", "python",
            "jupyter lab","conda activate","cp", "git status",
            "git diff", "git config", "git init", "git branch",
            "git log", "git merge", "git log", "git show",
            "git fetch", "git remote add", "git rebase", "git rm",
            "git mv", "git log", "git reset", "git rebase", "git stash"
            ],
        
        "python":
            ["if","elif","else","for","and","or","len",
            "str", "int","float", "==", "!=", "<=", ">=",
             "is" , "is not" ,"True","False",
             "pass","while", "print", "from", "import",
             "def", "return" ,
             "del","zip",
             "+=", "-=","*=","/=","%=",
             ".append",".insert",".remove",".sort","sorted()"
            ],
        
        "pandas":
            ["loc","iloc",
            ".Series","index=",".DataFrame","columns"
            ]
        }

#Initiate joke reward for high score
url = 'https://v2.jokeapi.dev/joke/Any?blacklistFlags=religious,political,racist,sexist&type=single'


#Begin Loop


# Initialise Inputs
new_input = ""
scores = 0
count = 0
keystroke_count = 11
char_list = "syntax"

#Game start
print("\n")
print("<-------------------------------------->\n\n\n")


#User input. Enter to start or type number or syntax eg (20, or python)
user_range = input("-------------- Press Enter ------------\n\n")
if user_range == "":
    user_range = keystroke_count

# User can type git to return git Syntax List
elif user_range == "git":
    char_list =  "git"

# User can type python to return python Syntax List
elif user_range == "python":
    char_list =  "python"

# User can type pandas to return pandas Syntax List
elif user_range == "pandas":
    char_list =  "pandas"

# User can type integer to extend game
elif int(user_range) > keystroke_count:
    keystroke_count = int(user_range)

#Start Countdown
time.sleep(.3)

print("\n")
print("3\n\n")

time.sleep(1)
print("2\n\n")

time.sleep(1)
print("1\n")

time.sleep(1)
print("> GO! >\n")


#Start the clock
start_time = time.perf_counter()

# Game will continue untile the user types "quit" or if count gets to keystroke_count (default 11)
while new_input != "quit" and count < keystroke_count :

    #Randomly choose a stroke from the list_
    key_ = random.choice(list_[char_list])
    print("-------\n")
    print(f"   {key_}")
    print("-------\n")

    #User inputs the matching key
    new_input = input("")
    count += 1

    #If the user input matches the key add 1 to total score
    if new_input == key_:
        scores += 1

#Once game is complete, stop the timer
stop_time = time.perf_counter()

#Calculate score and time paramaters

total_time = round(stop_time - start_time,2)
total_score = round((scores / count) * 100 ,2)

#Encourage player dialog
print ("<-------------------------------------->\n")

#High score will print a joke as reward
if total_score == 100:
    print("Perfect Accuracy\n")
if total_time < (keystroke_count * 1.35) and total_score == 100:
    print("High Score !!!\n")
    print("You earned a joke\n")

    # Execute get request
    requests.get(url)

    # Execute GET request and store response
    response_data = requests.get(url)

    # Get content
    response_content = response_data.content

    # Formatting as json
    data = response_data.json()
    
    # Parse joke
    if data["type"] == "twopart":
        joke = data["setup"] + "\n" + data["delivery"] + "\n"
    else:
        joke = data["joke"]  + "\n"
    print(joke)

#Other Encouragement
if total_score >= 80 and total_score < 100:
    print("Good Accuracy\n")
if total_time < (keystroke_count * 1.6) and total_score > 85 and total_score != 100:
    print("Great job speedy fingers!\n")

#Bad Score
if total_score == 0:
    print("Want to try that again?..\n")
if total_score < 75:
    print("You can do better?")
if total_time > (keystroke_count * 1.8):
    print("Pick up the pace")

#Print Results
print ("<-------------------------------------->\n")
print(f"Time: {total_time} seconds")
print(f"Accuracy {total_score}%\n\n")



# End Loop



# Keyboard Training by Dan Isaacman 